on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install protoc
      run: |
        set -e
        PROTOBUF_VERSION=3.12.3

        # Validates that the protos in this repo can be compiled.
        case "$OSTYPE" in
          linux*)
            PROTOBUF_PLATFORM=linux-x86_64
            PROTOC=tmp/bin/protoc
            ;;
          win* | msys* | cygwin*)
            PROTOBUF_PLATFORM=win64
            PROTOC=tmp/bin/protoc.exe
            ;;
          darwin*)
            PROTOBUF_PLATFORM=osx-x86_64
            PROTOC=tmp/bin/protoc
            ;;
          *)
            echo "Unknown OSTYPE: $OSTYPE"
            exit 1
        esac

        rm -rf tmp
        mkdir tmp
        cd tmp
        echo "- Downloading protobuf@$PROTOBUF_VERSION"
        curl -sSL \
          https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-$PROTOBUF_PLATFORM.zip \
          --output protobuf.zip
        unzip -q protobuf.zip
        cd ..

        echo "- Compiling protos as a descriptor set"
        chmod +x $PROTOC
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...